version: '3'
services:
  backend:
    container_name: movies_backend
    build:
      context: ./movies_admin
      dockerfile: Dockerfile
    networks: 
      - gateway
    ports:
      - 8000:8000
    env_file:
      - ./movies_admin/.env
    volumes:
      - static:/opt/app/static/
      - media:/opt/app/media/
    depends_on: 
      - postgres
    restart:
      on-failure

  postgres:
    container_name: movies_postgres
    build:
      context: .
      dockerfile: Dockerfile_db
    ports:
      - 5432:5432
    networks: 
      - gateway
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_postgres_data:/var/lib/postgresql/data/
    restart: on-failure

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
  #   networks: 
  #     - gateway
  #   ports:
  #     - 9200:9200
  #   restart: on-failure

  nginx:
    container_name: movies_nginx
    image: nginx:1.19.5
    networks: 
      - gateway
    ports: 
      - "80:80"
    volumes: 
      - ./movies_admin/src/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./movies_admin/src/configs:/etc/nginx/conf.d:ro
      - static:/var/www/static/:ro
      - media:/var/www/media/:ro
    restart: on-failure
    depends_on: 
      - backend
volumes:
  static:
  media:
  db_postgres_data:
networks:
  gateway: {}
